#!/usr/bin/env node
// scripts/build-config.js
// Reads env vars (from .env locally, or Vercel Environment Variables in production)
// and writes /config.js which exposes them on window.CABT_CONFIG.
//
// This file is loaded by index.html BEFORE any JSX, so api.jsx can read
// credentials at runtime without them being hardcoded in source.
//
// Run locally:  node scripts/build-config.js
// On Vercel:    runs automatically via vercel.json buildCommand.

const fs = require('fs');
const path = require('path');

// Load .env locally (Vercel injects env vars natively, no .env file needed)
function loadDotEnv() {
  const envPath = path.join(__dirname, '..', '.env');
  if (!fs.existsSync(envPath)) return;
  const lines = fs.readFileSync(envPath, 'utf8').split(/\r?\n/);
  for (const raw of lines) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq < 0) continue;
    const key = line.slice(0, eq).trim();
    let val = line.slice(eq + 1).trim();
    // Strip surrounding quotes
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    if (!(key in process.env)) process.env[key] = val;
  }
}

loadDotEnv();

const SUPABASE_URL      = process.env.SUPABASE_URL || '';
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || '';

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.error('[build-config] ⚠ Missing SUPABASE_URL or SUPABASE_ANON_KEY.');
  console.error('[build-config]   Local: copy .env.example to .env and fill in.');
  console.error('[build-config]   Vercel: add via Settings → Environment Variables.');
  // Don't fail the build — write an empty config so the page still loads
  // with a clear error instead of breaking the deploy.
}

const out = `// AUTO-GENERATED by scripts/build-config.js — do not edit, do not commit.
// Sourced from .env (local) or Vercel Environment Variables (production).
window.CABT_CONFIG = {
  SUPABASE_URL: ${JSON.stringify(SUPABASE_URL)},
  SUPABASE_ANON_KEY: ${JSON.stringify(SUPABASE_ANON_KEY)}
};
`;

const outPath = path.join(__dirname, '..', 'config.js');
fs.writeFileSync(outPath, out, 'utf8');
console.log('[build-config] ✓ wrote config.js (' + out.length + ' bytes)');
console.log('[build-config]   SUPABASE_URL:      ' + (SUPABASE_URL ? '✓ set' : '✗ MISSING'));
console.log('[build-config]   SUPABASE_ANON_KEY: ' + (SUPABASE_ANON_KEY ? '✓ set' : '✗ MISSING'));
